/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWorkloadRouteImport } from './routes/_authenticated/workload'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAttendanceRouteImport } from './routes/_authenticated/attendance'
import { Route as AuthenticatedJobCardsIndexRouteImport } from './routes/_authenticated/job-cards.index'
import { Route as AuthenticatedCarsIndexRouteImport } from './routes/_authenticated/cars.index'
import { Route as AuthenticatedJobCardsJobIdRouteImport } from './routes/_authenticated/job-cards.$jobId'
import { Route as AuthenticatedCarsCarIdRouteImport } from './routes/_authenticated/cars.$carId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWorkloadRoute = AuthenticatedWorkloadRouteImport.update({
  id: '/workload',
  path: '/workload',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAttendanceRoute = AuthenticatedAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobCardsIndexRoute =
  AuthenticatedJobCardsIndexRouteImport.update({
    id: '/job-cards/',
    path: '/job-cards/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarsIndexRoute = AuthenticatedCarsIndexRouteImport.update({
  id: '/cars/',
  path: '/cars/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJobCardsJobIdRoute =
  AuthenticatedJobCardsJobIdRouteImport.update({
    id: '/job-cards/$jobId',
    path: '/job-cards/$jobId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarsCarIdRoute = AuthenticatedCarsCarIdRouteImport.update({
  id: '/cars/$carId',
  path: '/cars/$carId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/workload': typeof AuthenticatedWorkloadRoute
  '/cars/$carId': typeof AuthenticatedCarsCarIdRoute
  '/job-cards/$jobId': typeof AuthenticatedJobCardsJobIdRoute
  '/cars/': typeof AuthenticatedCarsIndexRoute
  '/job-cards/': typeof AuthenticatedJobCardsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/attendance': typeof AuthenticatedAttendanceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/workload': typeof AuthenticatedWorkloadRoute
  '/cars/$carId': typeof AuthenticatedCarsCarIdRoute
  '/job-cards/$jobId': typeof AuthenticatedJobCardsJobIdRoute
  '/cars': typeof AuthenticatedCarsIndexRoute
  '/job-cards': typeof AuthenticatedJobCardsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/attendance': typeof AuthenticatedAttendanceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/workload': typeof AuthenticatedWorkloadRoute
  '/_authenticated/cars/$carId': typeof AuthenticatedCarsCarIdRoute
  '/_authenticated/job-cards/$jobId': typeof AuthenticatedJobCardsJobIdRoute
  '/_authenticated/cars/': typeof AuthenticatedCarsIndexRoute
  '/_authenticated/job-cards/': typeof AuthenticatedJobCardsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/attendance'
    | '/dashboard'
    | '/employees'
    | '/workload'
    | '/cars/$carId'
    | '/job-cards/$jobId'
    | '/cars/'
    | '/job-cards/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/attendance'
    | '/dashboard'
    | '/employees'
    | '/workload'
    | '/cars/$carId'
    | '/job-cards/$jobId'
    | '/cars'
    | '/job-cards'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/attendance'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees'
    | '/_authenticated/workload'
    | '/_authenticated/cars/$carId'
    | '/_authenticated/job-cards/$jobId'
    | '/_authenticated/cars/'
    | '/_authenticated/job-cards/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/workload': {
      id: '/_authenticated/workload'
      path: '/workload'
      fullPath: '/workload'
      preLoaderRoute: typeof AuthenticatedWorkloadRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/attendance': {
      id: '/_authenticated/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthenticatedAttendanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/job-cards/': {
      id: '/_authenticated/job-cards/'
      path: '/job-cards'
      fullPath: '/job-cards/'
      preLoaderRoute: typeof AuthenticatedJobCardsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cars/': {
      id: '/_authenticated/cars/'
      path: '/cars'
      fullPath: '/cars/'
      preLoaderRoute: typeof AuthenticatedCarsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/job-cards/$jobId': {
      id: '/_authenticated/job-cards/$jobId'
      path: '/job-cards/$jobId'
      fullPath: '/job-cards/$jobId'
      preLoaderRoute: typeof AuthenticatedJobCardsJobIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cars/$carId': {
      id: '/_authenticated/cars/$carId'
      path: '/cars/$carId'
      fullPath: '/cars/$carId'
      preLoaderRoute: typeof AuthenticatedCarsCarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAttendanceRoute: typeof AuthenticatedAttendanceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedWorkloadRoute: typeof AuthenticatedWorkloadRoute
  AuthenticatedCarsCarIdRoute: typeof AuthenticatedCarsCarIdRoute
  AuthenticatedJobCardsJobIdRoute: typeof AuthenticatedJobCardsJobIdRoute
  AuthenticatedCarsIndexRoute: typeof AuthenticatedCarsIndexRoute
  AuthenticatedJobCardsIndexRoute: typeof AuthenticatedJobCardsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAttendanceRoute: AuthenticatedAttendanceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedWorkloadRoute: AuthenticatedWorkloadRoute,
  AuthenticatedCarsCarIdRoute: AuthenticatedCarsCarIdRoute,
  AuthenticatedJobCardsJobIdRoute: AuthenticatedJobCardsJobIdRoute,
  AuthenticatedCarsIndexRoute: AuthenticatedCarsIndexRoute,
  AuthenticatedJobCardsIndexRoute: AuthenticatedJobCardsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
